# general
use_gpu: True
gpu_id: 0
seed: 19971010
state: INFO
dataset: wizard_ramdon_split
model: ELMER
retrieval: False
reproducibility: True
train: True

# dataset and model
data_dir: 'data/wizard_of_wikipedia_random_split'
pretrained_model_dir: 'pretrained_model/elmer'
saved_dir: 'saved_model'
log_dir: 'logging'

# training settings
start_epoch: 0
epochs: 100
train_batch_size: 16
optimizer: adam
lr: 2e-5

# evaluation settings
eval_batch_size: 32

# testing settings
test_batch_size: 16
finetuned_model_dir: 'pretrained_model/elmer'
output_dir: 'output_text'
